TeamProject (Book Reservation)/MVCProject/Controllers/BookCollectionController.cs
using BL.DTOs.ConnectionTables;
using BL.DTOs.Entities.BookCollection;
using BL.Facades;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVCProject.Config;
using System.Threading.Tasks;

namespace MVCProject.Controllers
{
    public class BookCollectionController : Controller
    {
        private readonly BookCollectionFacade _bookCollectionFacade;

        public BookCollectionController(BookCollectionFacade facade)
        {
            _bookCollectionFacade = facade;
        }

        // GET: BookCollection
        public async Task<IActionResult> Index()
        {
            if (!User.IsInRole(GlobalConstants.AdminRoleName))
            {
                return NotFound();
            }

            var bookCollections = await _bookCollectionFacade.GetAllBookCollections();

            return View(bookCollections.Item1);
        }

        // GET: BookCollection/UserCollections
        public async Task<IActionResult> UserCollections()
        {
            if (!User.IsInRole(GlobalConstants.UserRoleName))
            {
                return NotFound();
            }

            int userId = int.Parse(User.Identity.Name);

            return View(await _bookCollectionFacade.GetBookCollectionPrevsByUser(userId));
        }


        // GET: BookCollection/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || (!User.IsInRole(GlobalConstants.UserRoleName) && !User.IsInRole(GlobalConstants.AdminRoleName)))
            {
                return NotFound();
            }

            var bookCollection = await _bookCollectionFacade.GetBookCollectionWithBooksAndOwner(id.Value);
            if (bookCollection == null || (bookCollection.UserId != int.Parse(User.Identity.Name) && !User.IsInRole(GlobalConstants.AdminRoleName)))
            {
                return NotFound();
            }

            ViewData["books"] = await _bookCollectionFacade.GetBookPreviewsWithAuthorsForCollection(bookCollection);

            return View(bookCollection);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Details(int bookCollectionId, int bookToDeleteId)
        {
            if (!User.IsInRole(GlobalConstants.UserRoleName) && !User.IsInRole(GlobalConstants.AdminRoleName))
            {
                return NotFound();
            }

            var bookCollection = await _bookCollectionFacade.Get(bookCollectionId);
            if (bookCollection == null || (bookCollection.UserId != int.Parse(User.Identity.Name) && !User.IsInRole(GlobalConstants.AdminRoleName)))
            {
                return NotFound();
            }

            _bookCollectionFacade.DeleteBookFromCollection(bookCollectionId, bookToDeleteId);

            return RedirectToAction(nameof(Details), new { id = bookCollectionId });
        }

        // GET: BookCollection/UserCreateCollection
        [HttpGet]
        public IActionResult UserCreateCollection(int? id)
        {
            if (!User.IsInRole(GlobalConstants.UserRoleName))
            {
                return NotFound();
            }

            return View();
        }

        // POST: BookCollection/UserCreateCollection
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UserCreateCollection([Bind("Title,Description")] BookCollectionCreateDTO bookCollection)
        {
            if (!User.IsInRole(GlobalConstants.UserRoleName))
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                return View(bookCollection);
            }

            int userId;
            if (User.Identity.Name is not null)
            {
                userId = int.Parse(User.Identity.Name);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

            await _bookCollectionFacade.CreateUserCollection(bookCollection, userId);
            return RedirectToAction(nameof(UserCollections));
        }

        // GET: BookCollection/UserAddBookInCollection
        public async Task<IActionResult> UserAddBookInCollection(int? id)
        {
            if (!User.IsInRole(GlobalConstants.UserRoleName) || id == null)
            {
                return NotFound();
            }

            bool existsBook = await _bookCollectionFacade.DoesBookExist(id.Value);
            if (!existsBook)
            {
                return NotFound();
            }

            int userId = int.Parse(User.Identity.Name);

            var collectionPrevs = await _bookCollectionFacade.GetBookCollectionPrevsByUser(userId);

            ViewData["collections"] = collectionPrevs;
            return View();
        }

        // POST: BookCollection/UserAddBookInCollection
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UserAddBookInCollection(int? id, [Bind("BookCollectionID")] AddBookInCollectionDTO bookCollectionBook)
        {
            if (id is null || !User.IsInRole(GlobalConstants.UserRoleName))
            {
                return NotFound();
            }

            bool existsBook = await _bookCollectionFacade.DoesBookExist(id.Value);
            if (!existsBook)
            {
                return NotFound();
            }

            bookCollectionBook.BookID = (int)id;

            var bookCollection = await _bookCollectionFacade.Get(bookCollectionBook.BookCollectionID);
            if (bookCollection == null || (bookCollection.UserId != int.Parse(User.Identity.Name) && !User.IsInRole(GlobalConstants.AdminRoleName)))
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _bookCollectionFacade.AddBookToCollection(bookCollectionBook);
                return RedirectToAction(nameof(Details), new { id = bookCollectionBook.BookCollectionID });
            }

            return View(bookCollectionBook);
        }

        // GET: BookCollection/UserEditCollection/5
        public async Task<IActionResult> UserEditCollection(int? id)
        {
            if (id == null || !User.IsInRole(GlobalConstants.UserRoleName))
            {
                return NotFound();
            }

            int userId = int.Parse(User.Identity.Name);

            var bookCollection = await _bookCollectionFacade.GetUserCollectionToEdit((int)id);

            if (bookCollection == null || (bookCollection.UserId != userId))
            {
                return NotFound();
            }

            return View(bookCollection);
        }

        // POST: BookCollection/UserEditCollection/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UserEditCollection(int? id, [Bind("Title,Description,Id,UserId,CreationDate")] BookCollectionCreateDTO bookCollection)
        {
            if (id != bookCollection.Id || !User.IsInRole(GlobalConstants.UserRoleName))
            {
                return NotFound();
            }

            int userId = int.Parse(User.Identity.Name);

            if (bookCollection == null || (bookCollection.UserId != userId))
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                return View(bookCollection);
            }

            try
            {
                _bookCollectionFacade.UserEditCollection(bookCollection);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!await BookCollectionExists(bookCollection.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToAction(nameof(Details), new { id = bookCollection.Id });
        }

        // GET: BookCollection/Create
        public IActionResult Create()
        {
            if (!User.IsInRole(GlobalConstants.AdminRoleName))
            {
                return NotFound();
            }

            return View();
        }

        // POST: BookCollection/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,Description,CreationDate,UserId,Id")] BookCollectionDTO bookCollection)
        {
            if (!User.IsInRole(GlobalConstants.AdminRoleName))
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _bookCollectionFacade.Create(bookCollection);
                return RedirectToAction(nameof(Index));
            }

            return View(bookCollection);
        }

        // GET: BookCollection/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || !User.IsInRole(GlobalConstants.AdminRoleName))
            {
                return NotFound();
            }

            var bookCollection = await _bookCollectionFacade.Get((int)id);

            if (bookCollection == null)
            {
                return NotFound();
            }

            return View(bookCollection);
        }

        // POST: BookCollection/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Title,Description,CreationDate,UserId,Id")] BookCollectionDTO bookCollection)
        {
            if (id != bookCollection.Id || !User.IsInRole(GlobalConstants.AdminRoleName))
            {

TeamProject (Book Reservation)/MVCProject/Views/BookCollection/Create.cshtml
@model BL.DTOs.Entities.BookCollection.BookCollectionDTO

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>BookCollection</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreationDate" class="control-label"></label>
                <input asp-for="CreationDate" class="form-control" />
                <span asp-validation-for="CreationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TeamProject (Book Reservation)/MVCProject/Views/BookCollection/Delete.cshtml
@model BL.DTOs.Entities.BookCollection.BookCollectionDTO

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BookCollection</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Details" asp-route-id="@Model.Id">Back to Detail</a>
    </form>
</div>

TeamProject (Book Reservation)/MVCProject/Views/BookCollection/Details.cshtml
@model BL.DTOs.Entities.BookCollection.BookCollectionDTO
@using MVCProject.Config;

@{
    ViewData["Title"] = "Details";
}

<h1>Book Collection</h1>
<hr />
<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
    </dl>

    <h5>Owner</h5>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.OwnerUser.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OwnerUser.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.OwnerUser.Surname)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OwnerUser.Surname)
        </dd>
    </dl>

    <div>
        @if (ViewContext.HttpContext.User.IsInRole(GlobalConstants.UserRoleName) && Model.UserId == int.Parse(User.Identity.Name))
        {
            <div>
                <a asp-action="UserEditCollection" asp-route-id="@Model.Id">Edit my collection</a>
                <a asp-action="UserCollections"> | Back to my books collections</a>
            </div>
        }

        @if (ViewContext.HttpContext.User.IsInRole(GlobalConstants.AdminRoleName))
        {
            <div>
                <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
                <a asp-action="Index"> | Back to all book collections</a>
            </div>
        }
        @if (ViewContext.HttpContext.User.IsInRole(GlobalConstants.AdminRoleName) ||
            ViewContext.HttpContext.User.IsInRole(GlobalConstants.UserRoleName) && Model.UserId == int.Parse(User.Identity.Name))
        {
            <div>
                <a asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
            </div>
        }

        <br />

        <h5>Books</h5>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @String.Format("Title")
                    </th>
                    <th>
                        @String.Format("Authors")
                    </th>
                    <th>
                        @String.Format("Language")
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var book in (IEnumerable<BL.DTOs.Entities.Book.BookPrevDTO>)ViewData["books"])
                {
                    <tr>
                        <td>
                            @book.Title
                        </td>
                        <td>
                            @String.Join(", ", book.Authors.Select(x => x.Author.Name + " " + x.Author.Surname))
                        </td>
                        <td>
                            @book.Language
                        </td>
                        <td>
                            <form asp-action="Details">
                                <input type="hidden" name="bookCollectionId" value=@Model.Id>
                                <input type="hidden" name="bookToDeleteId" value=@book.Id>
                                <input type="submit" value="Delete" class="btn btn-danger" />
                            </form>
                            <a asp-controller="Book" asp-action="Details" asp-route-id="@book.Id">Details</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

TeamProject (Book Reservation)/MVCProject/Views/BookCollection/Edit.cshtml
@model BL.DTOs.Entities.BookCollection.BookCollectionDTO

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>BookCollection</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreationDate" class="control-label"></label>
                <input asp-for="CreationDate" class="form-control" />
                <span asp-validation-for="CreationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control">
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TeamProject (Book Reservation)/MVCProject/Views/BookCollection/Index.cshtml
@model IEnumerable<BL.DTOs.Entities.BookCollection.BookCollectionDTO>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OwnerUser)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

TeamProject (Book Reservation)/MVCProject/Views/BookCollection/UserAddBookInCollection.cshtml
@model BL.DTOs.ConnectionTables.AddBookInCollectionDTO

@{
    ViewData["Title"] = "AddBookInCollection";
}

<h1>Choose collection:</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="UserAddBookInCollection">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="BookCollectionID" class="control-label">Book collection</label>
                <select asp-for="BookCollectionID" class="form-control" name="BookCollectionID">
                    <option value="">Please select</option>
                    @foreach (var collection in (IEnumerable<BL.DTOs.Entities.BookCollection.BookCollectionPrevDTO>)ViewData["collections"])
                    {
                        <option value="@collection.Id">@collection.Title</option>
                    }
                </select>
            </div>

            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Book" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TeamProject (Book Reservation)/MVCProject/Views/BookCollection/UserCollections.cshtml
@model IEnumerable<BL.DTOs.Entities.BookCollection.BookCollectionPrevDTO>

@{
    ViewData["Title"] = "Index";
}

<h1>My Book Collections</h1>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id">Details</a>
            </td>
        </tr>
}
    </tbody>
</table>
<p>
    <input type="button" class="btn btn-primary" value="Create" onclick="location.href='@Url.Action("UserCreateCollection", "BookCollection")'" />
</p>

TeamProject (Book Reservation)/MVCProject/Views/BookCollection/UserCreateCollection.cshtml
@model BL.DTOs.Entities.BookCollection.BookCollectionCreateDTO

@{
    ViewData["Title"] = "Create";
}

<h1>Create book collection</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="UserCreateCollection">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="UserCollections">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TeamProject (Book Reservation)/MVCProject/Views/BookCollection/UserEditCollection.cshtml
@model BL.DTOs.Entities.BookCollection.BookCollectionCreateDTO

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>BookCollection</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="UserEditCollection">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="CreationDate" />
            <input type="hidden" asp-for="UserId" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Details" asp-route-id="@Model.Id">Back to Detail</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}