TeamProject (Book Reservation)/MVCProject/Controllers/AuthorController.cs
using BL.DTOs.Entities.Author;
using BL.Facades;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVCProject.Config;
using MVCProject.Models;
using MVCProject.StateManager;
using MVCProject.StateManager.FilterStates;
using System.Threading.Tasks;

namespace MVCProject.Controllers
{
    public class AuthorController : BaseController
    {
        private readonly AuthorFacade _facade;

        public AuthorController(AuthorFacade facade)
        {
            _facade = facade;
        }

        // GET: Author
        public async Task<IActionResult> Index(int page = 1)
        {
            var authorFilterState = TempData.Get<AuthorFilterState>(TempDataKeys.AuthorFilter.ToString());
            if (authorFilterState == null)
            {
                authorFilterState = new AuthorFilterState();
            }

            SetViewDataForIndex(authorFilterState);

            var model = await _facade.GetAuthorPreviews(page, PageSize, authorFilterState.Name, authorFilterState.Surname);


            var pagedModel = new PagedListViewModel<AuthorPrevDTO>(new PaginationViewModel(page, model.Item2, PageSize),
                                                                 model.Item1);

            TempData.Put<AuthorFilterState>(TempDataKeys.AuthorFilter.ToString(), authorFilterState);
            return View(pagedModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(int page, string name, string surname)
        {
            page = 1;
            var authorFilterState = new AuthorFilterState()
            {
                Name = name,
                Surname = surname
            };

            SetViewDataForIndex(authorFilterState);

            var model = await _facade.GetAuthorPreviews(page, PageSize, authorFilterState.Name, authorFilterState.Surname);


            var pagedModel = new PagedListViewModel<AuthorPrevDTO>(new PaginationViewModel(page, model.Item2, PageSize),
                                                                 model.Item1);

            TempData.Put<AuthorFilterState>(TempDataKeys.AuthorFilter.ToString(), authorFilterState);

            return View(pagedModel);
        }

        private void SetViewDataForIndex(AuthorFilterState authorFilterState)
        {
            ViewData["name"] = authorFilterState.Name;
            ViewData["surname"] = authorFilterState.Surname;
        }

        // GET: Author/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _facade.Get(id.Value);
            if (author == null)
            {
                return NotFound();
            }

            author.AuthorsBooks = await _facade.GetAuthorBooksByAuthor((int)id);

            return View(author);
        }

        // GET: Author/Create
        public IActionResult Create()
        {
            if (!User.IsInRole(GlobalConstants.AdminRoleName))
            {
                return NotFound();
            }

            return View();
        }

        // POST: Author/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AuthorDTO author)
        {
            if (!User.IsInRole(GlobalConstants.AdminRoleName))
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _facade.Create(author);
                return RedirectToAction(nameof(Index));
            }

            return View(author);
        }

        // GET: Author/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || !User.IsInRole(GlobalConstants.AdminRoleName))
            {
                return NotFound();
            }

            var author = await _facade.Get(id.Value);
            if (author == null)
            {
                return NotFound();
            }

            author.AuthorsBooks = await _facade.GetAuthorBooksByAuthor((int)id);

            return View(author);
        }

        // POST: Author/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Surname,Description,Id")] AuthorDTO author)
        {
            if (id != author.Id || !User.IsInRole(GlobalConstants.AdminRoleName))
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                return View(author);
            }

            try
            {
                _facade.Update(author);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!await AuthorExists(author.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Details), new { id = id });
        }

        // GET: Authors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || !User.IsInRole(GlobalConstants.AdminRoleName))
            {
                return NotFound();
            }

            var author = await _facade.Get(id.Value);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            if (!User.IsInRole(GlobalConstants.AdminRoleName))
            {
                return NotFound();
            }

            _facade.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> AuthorExists(int id)
        {
            var author = await _facade.Get(id);
            return author != null;
        }
    }
}

TeamProject (Book Reservation)/MVCProject/Controllers/EReaderInstanceController.cs
using BL.DTOs.ConnectionTables;
using BL.DTOs.Entities.EReaderInstance;
using BL.Facades;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVCProject.Config;
using MVCProject.Models;
using MVCProject.StateManager;
using MVCProject.StateManager.FilterStates;
using System.Linq;
using System.Threading.Tasks;

namespace MVCProject.Controllers
{
    public class EReaderInstanceController : BaseController
    {
        private readonly EReaderInstanceFacade _eReaderInstanceFacade;

        public EReaderInstanceController(EReaderInstanceFacade facade)
        {
            _eReaderInstanceFacade = facade;
        }

        // GET: EReaderInstance
        [HttpGet]
        public async Task<IActionResult> Index(int page = 1)
        {
            var eReaderInstanceFilterState = TempData.Get<EReaderInstanceFilterState>(TempDataKeys.EReaderInstanceFilterState.ToString());
            if (eReaderInstanceFilterState == null)
            {
                eReaderInstanceFilterState = new EReaderInstanceFilterState();
            }

            SetViewDataForIndex(eReaderInstanceFilterState);

            var model = await _eReaderInstanceFacade.GetEReaderInstancePrevsBy(page, PageSize, eReaderInstanceFilterState.Description,
                eReaderInstanceFilterState.Company, eReaderInstanceFilterState.Model, eReaderInstanceFilterState.MemoryFrom,
                eReaderInstanceFilterState.MemoryTo);


            var pagedModel = new PagedListViewModel<EReaderInstancePrevDTO>(new PaginationViewModel(page, model.Item2, PageSize),
                                                                 model.Item1);

            TempData.Put<EReaderInstanceFilterState>(TempDataKeys.EReaderInstanceFilterState.ToString(), eReaderInstanceFilterState);
            return View(pagedModel);
        }

        // POST: EReaderInstance
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(int page,
                                               string description,
                                               string company,
                                               string model,
                                               int? memoryFrom,
                                               int? memoryTo)
        {
            page = 1;
            var eReaderInstanceFilterState = new EReaderInstanceFilterState()
            {
                Description = description,
                Company = company,
                Model = model,
                MemoryFrom = memoryFrom,
                MemoryTo = memoryTo
            };

            SetViewDataForIndex(eReaderInstanceFilterState);

            var resModel = await _eReaderInstanceFacade.GetEReaderInstancePrevsBy(page, PageSize, eReaderInstanceFilterState.Description,
                eReaderInstanceFilterState.Company, eReaderInstanceFilterState.Model, eReaderInstanceFilterState.MemoryFrom,
                eReaderInstanceFilterState.MemoryTo);


            var pagedModel = new PagedListViewModel<EReaderInstancePrevDTO>(new PaginationViewModel(page, resModel.Item2, PageSize),
                                                                 resModel.Item1);

            TempData.Put<EReaderInstanceFilterState>(TempDataKeys.EReaderInstanceFilterState.ToString(), eReaderInstanceFilterState);
            return View(pagedModel);
        }

        private void SetViewDataForIndex(EReaderInstanceFilterState authorFilterState)
        {
            ViewData["description"] = authorFilterState.Description;
            ViewData["company"] = authorFilterState.Company;
            ViewData["model"] = authorFilterState.Model;
            ViewData["memoryFrom"] = authorFilterState.MemoryFrom;
            ViewData["memoryTo"] = authorFilterState.MemoryTo;
        }

        // GET: UserEReaders
        [HttpGet]
        public async Task<IActionResult> UserEReaders()
        {
            if (!User.IsInRole(GlobalConstants.UserRoleName))
            {
                return NotFound();
            }

            int userId = int.Parse(User.Identity.Name);

            return View(await _eReaderInstanceFacade.GetEReaderInstancesByOwner(userId));
        }

        // GET: EReaderInstance/UserAddEBookInEReader
        public IActionResult UserAddEBookInEReader()
        {
            if (!User.IsInRole(GlobalConstants.UserRoleName))
            {
                return NotFound();
            }

            int userId = int.Parse(User.Identity.Name);

            var eReaders = _eReaderInstanceFacade.GetEReaderInstancesByOwner(userId).Result;

            ViewData["eReaders"] = eReaders;
            return View();
        }

        // POST: EReaderInstance/UserAddEBookInEReader
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UserAddEBookInEReader(int? id, [Bind("EReaderInstanceID")] AddEBookInEReaderInstanceDTO eReaderEbook)
        {
            if (id is null || !User.IsInRole(GlobalConstants.UserRoleName))
            {
                return NotFound();
            }

            var eReaderExists = await EReaderInstanceExists(eReaderEbook.EReaderInstanceID);
            if (!eReaderExists)
            {
                return NotFound();
            }

            eReaderEbook.EBookID = id.Value;
            if (await _eReaderInstanceFacade.CheckIfAlreadyHasBook(eReaderEbook.EReaderInstanceID, id.Value))
            {
                return RedirectToAction(nameof(Details), new { id = eReaderEbook.EReaderInstanceID });
            }

            if (ModelState.IsValid)
            {
                await _eReaderInstanceFacade.AddEBook(eReaderEbook);
                return RedirectToAction(nameof(Details), new { id = eReaderEbook.EReaderInstanceID });
            }
            return View(eReaderEbook);
        }

        // GET: EReaderInstance/UserCreateEReader
        public IActionResult UserCreateEReader()
        {
            if (!User.IsInRole(GlobalConstants.UserRoleName))
            {
                return NotFound();
            }

            ViewData["eReaderTemplates"] = _eReaderInstanceFacade.GetEReaderTemplates().Result;
            return View();
        }

        // POST: EReaderInstance/UserCreateEReader
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UserCreateEReader([Bind("Description, EReaderTemplateID")] EReaderInstanceCreateDTO eReaderInstance)
        {
            if (!User.IsInRole(GlobalConstants.UserRoleName))
            {
                return NotFound();
            }

            int userId = int.Parse(User.Identity.Name);

            if (ModelState.IsValid)
            {
                await _eReaderInstanceFacade.AddNewEReaderToUser(eReaderInstance, userId);
                return RedirectToAction(nameof(UserEReaders));
            }

            return View(eReaderInstance);
        }

        // GET: EReaderInstance/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eReaderInstance = await GetWithReferences(id.Value);
            if (eReaderInstance == null)
            {
                return NotFound();
            }

            var loadedBooks = await _eReaderInstanceFacade.GetEBookEReaderInstancesByEReaderInstance(id.Value);
            eReaderInstance.BooksIncluded = loadedBooks;
            ViewData["eBooks"] = loadedBooks.Select(entry => entry.EBook);

            return View(eReaderInstance);
        }

        [HttpPost]
        public async Task<IActionResult> Details(int eReaderToModifyId, int eBookToDeleteId)
        {
            if (!User.IsInRole(GlobalConstants.UserRoleName) && !User.IsInRole(GlobalConstants.AdminRoleName))
            {
                return NotFound();
            };

            var eReaderInstance = await _eReaderInstanceFacade.Get(eReaderToModifyId);
            if (eReaderInstance == null || (eReaderInstance.EreaderOwnerId != int.Parse(User.Identity.Name)
                && !User.IsInRole(GlobalConstants.AdminRoleName)))
            {
                return NotFound();
            }

            _eReaderInstanceFacade.DeleteEBook(eReaderToModifyId, eBookToDeleteId);

            return RedirectToAction("Details", new { id = eReaderToModifyId });
        }

        // GET: EReaderInstance/Create
        public IActionResult Create()
        {
            if (!User.IsInRole(GlobalConstants.AdminRoleName))
            {
                return NotFound();
            };

            return View();
        }

        // POST: EReaderInstance/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Description,EreaderOwnerId,EReaderTemplateID,Id")] EReaderInstanceDTO eReaderInstance)
        {
            if (!User.IsInRole(GlobalConstants.AdminRoleName))
            {
                return NotFound();
            };

            if (ModelState.IsValid)
            {
                await _eReaderInstanceFacade.Create(eReaderInstance);
                return RedirectToAction(nameof(Index));
            }

            return View(eReaderInstance);
        }

        // GET: EReaderInstance/UserEditBookInstance/5
        public async Task<IActionResult> UserEditEReaderInstance(int? id)
        {
            if (id == null || !User.IsInRole(GlobalConstants.UserRoleName))
            {
                return NotFound();
            }

            var eReaderInstance = await GetWithReferences(id.Value);
            if (eReaderInstance == null || (int.Parse(User.Identity.Name) != eReaderInstance.EreaderOwnerId))
            {
                return NotFound();
            }

TeamProject (Book Reservation)/MVCProject/Views/EBook/Create.cshtml
@model BL.DTOs.Entities.EBook.EBookDTO
@using BL.DTOs.Enums

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>EBook</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MemorySize" class="control-label"></label>
                <input asp-for="MemorySize" class="form-control" />
                <span asp-validation-for="MemorySize" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Format" class="control-label"></label>
                <select asp-for="Format" class="form-control" asp-items="Html.GetEnumSelectList<EBookFormatDTO>()"></select>
                <span asp-validation-for="Format" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ISBN" class="control-label"></label>
                <input asp-for="ISBN" class="form-control" />
                <span asp-validation-for="ISBN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PageCount" class="control-label"></label>
                <input asp-for="PageCount" class="form-control" />
                <span asp-validation-for="PageCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfRelease" class="control-label"></label>
                <input asp-for="DateOfRelease" class="form-control" />
                <span asp-validation-for="DateOfRelease" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Language" class="control-label"></label>
                <select asp-for="Language" class="form-control" asp-items="Html.GetEnumSelectList<LanguageDTO>()"></select>
                <span asp-validation-for="Language" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TeamProject (Book Reservation)/MVCProject/Views/EBook/Delete.cshtml
@model BL.DTOs.Entities.EBook.EBookDTO
@using BL.DTOs.Enums;

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EBook</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ISBN)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PageCount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PageCount)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfRelease)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateOfRelease)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Language)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Language)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MemorySize)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MemorySize)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Format)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Format)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TeamProject (Book Reservation)/MVCProject/Views/EBook/Details.cshtml
@model BL.DTOs.Entities.EBook.EBookDTO
@using BL.DTOs.Enums;
@using MVCProject.Config;

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>EBook</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ISBN)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PageCount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PageCount)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfRelease)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateOfRelease)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Language)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Language)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MemorySize)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MemorySize)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Format)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Format)
        </dd>
    </dl>
</div>
<div>
    @if (User.IsInRole(GlobalConstants.AdminRoleName))
    {
        <p>
            <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
            <a asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
        </p>
    }
    <a asp-action="Index">Back to List</a>
</div>

TeamProject (Book Reservation)/MVCProject/Views/EBook/Edit.cshtml
@model BL.DTOs.Entities.EBook.EBookDTO
@using BL.DTOs.Enums

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>EBook</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MemorySize" class="control-label"></label>
                <input asp-for="MemorySize" class="form-control" />
                <span asp-validation-for="MemorySize" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Format" class="control-label"></label>
                <select asp-for="Format" class="form-control" asp-items="Html.GetEnumSelectList<EBookFormatDTO>()"></select>
                <span asp-validation-for="Format" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ISBN" class="control-label"></label>
                <input asp-for="ISBN" class="form-control" />
                <span asp-validation-for="ISBN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PageCount" class="control-label"></label>
                <input asp-for="PageCount" class="form-control" />
                <span asp-validation-for="PageCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfRelease" class="control-label"></label>
                <input asp-for="DateOfRelease" class="form-control" />
                <span asp-validation-for="DateOfRelease" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Language" class="control-label"></label>
                <select asp-for="Language" class="form-control" asp-items="Html.GetEnumSelectList<LanguageDTO>()"></select>
                <span asp-validation-for="Language" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TeamProject (Book Reservation)/MVCProject/Views/EBook/Index.cshtml
@using BL.DTOs.Entities.EBook
@model PagedListViewModel<EBookPrevDTO>
@using MVCProject.Config;
@{
    ViewData["Title"] = "Index";
}

<h1>E-Books</h1>

<div class="float-container" style="width: 80vw">
    @await Html.PartialAsync("~/Views/BookFilter/_PartialBookFilter.cshtml")

    <div class="float-child-content">
        @if (User.IsInRole(GlobalConstants.AdminRoleName))
        {
            <p>
                <a asp-action="Create">Create New</a>
            </p>
        }

        <table class="table">

            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.List.FirstOrDefault().Title)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.List.FirstOrDefault().Authors)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.List.FirstOrDefault().Description)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.List.FirstOrDefault().Language)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.List.FirstOrDefault().Format)
                    </th>
                    <th class="col-3"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.List)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Title)
                        </td>
                        <td>
                            @foreach (var author in item.Authors)
                            {
                                <a asp-controller="Author" asp-action="Details" asp-route-id="@author.AuthorID">
                                    @Html.DisplayFor(modelItem => author.Author.Name) @Html.DisplayFor(modelItem => author.Author.Surname)
                                </a>
                            }
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Language)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Format)
                        </td>
                        <td>
                            <div>
                                <a asp-action="Details" asp-route-id="@item.Id">Details</a>
                                <br />
                                <a asp-controller="EReaderInstance" asp-action="UserAddEBookInEReader" asp-route-id="@item.Id">Add in E-Reader</a>
                                <br />
                            </div>

                            @if (User.IsInRole(GlobalConstants.AdminRoleName))
                            {
                                <div>
                                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                                    <br />
                                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                                </div>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div>
            @{
                await Html.RenderPartialAsync("_PaginationPartial", Model.Pagination);
            }
        </div>
    </div>
</div>