TeamProject (Book Reservation)/MVCProject/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using MVCProject.Config;

namespace MVCProject.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Main()
        {
            if (!User.IsInRole(GlobalConstants.AdminRoleName))
            {
                return NotFound();
            }

            return View();
        }
    }
}

TeamProject (Book Reservation)/MVCProject/Controllers/AuthorController.cs
using BL.DTOs.Entities.Author;
using BL.Facades;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVCProject.Config;
using MVCProject.Models;
using MVCProject.StateManager;
using MVCProject.StateManager.FilterStates;
using System.Threading.Tasks;

namespace MVCProject.Controllers
{
    public class AuthorController : BaseController
    {
        private readonly AuthorFacade _facade;

        public AuthorController(AuthorFacade facade)
        {
            _facade = facade;
        }

        // GET: Author
        public async Task<IActionResult> Index(int page = 1)
        {
            var authorFilterState = TempData.Get<AuthorFilterState>(TempDataKeys.AuthorFilter.ToString());
            if (authorFilterState == null)
            {
                authorFilterState = new AuthorFilterState();
            }

            SetViewDataForIndex(authorFilterState);

            var model = await _facade.GetAuthorPreviews(page, PageSize, authorFilterState.Name, authorFilterState.Surname);


            var pagedModel = new PagedListViewModel<AuthorPrevDTO>(new PaginationViewModel(page, model.Item2, PageSize),
                                                                 model.Item1);

            TempData.Put<AuthorFilterState>(TempDataKeys.AuthorFilter.ToString(), authorFilterState);
            return View(pagedModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(int page, string name, string surname)
        {
            page = 1;
            var authorFilterState = new AuthorFilterState()
            {
                Name = name,
                Surname = surname
            };

            SetViewDataForIndex(authorFilterState);

            var model = await _facade.GetAuthorPreviews(page, PageSize, authorFilterState.Name, authorFilterState.Surname);


            var pagedModel = new PagedListViewModel<AuthorPrevDTO>(new PaginationViewModel(page, model.Item2, PageSize),
                                                                 model.Item1);

            TempData.Put<AuthorFilterState>(TempDataKeys.AuthorFilter.ToString(), authorFilterState);

            return View(pagedModel);
        }

        private void SetViewDataForIndex(AuthorFilterState authorFilterState)
        {
            ViewData["name"] = authorFilterState.Name;
            ViewData["surname"] = authorFilterState.Surname;
        }

        // GET: Author/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _facade.Get(id.Value);
            if (author == null)
            {
                return NotFound();
            }

            author.AuthorsBooks = await _facade.GetAuthorBooksByAuthor((int)id);

            return View(author);
        }

        // GET: Author/Create
        public IActionResult Create()
        {
            if (!User.IsInRole(GlobalConstants.AdminRoleName))
            {
                return NotFound();
            }

            return View();
        }

        // POST: Author/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AuthorDTO author)
        {
            if (!User.IsInRole(GlobalConstants.AdminRoleName))
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _facade.Create(author);
                return RedirectToAction(nameof(Index));
            }

            return View(author);
        }

        // GET: Author/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || !User.IsInRole(GlobalConstants.AdminRoleName))
            {
                return NotFound();
            }

            var author = await _facade.Get(id.Value);
            if (author == null)
            {
                return NotFound();
            }

            author.AuthorsBooks = await _facade.GetAuthorBooksByAuthor((int)id);

            return View(author);
        }

        // POST: Author/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Surname,Description,Id")] AuthorDTO author)
        {
            if (id != author.Id || !User.IsInRole(GlobalConstants.AdminRoleName))
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                return View(author);
            }

            try
            {
                _facade.Update(author);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!await AuthorExists(author.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Details), new { id = id });
        }

        // GET: Authors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || !User.IsInRole(GlobalConstants.AdminRoleName))
            {
                return NotFound();
            }

            var author = await _facade.Get(id.Value);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            if (!User.IsInRole(GlobalConstants.AdminRoleName))
            {
                return NotFound();
            }

            _facade.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> AuthorExists(int id)
        {
            var author = await _facade.Get(id);
            return author != null;
        }
    }
}

TeamProject (Book Reservation)/MVCProject/Controllers/BookController.cs
using BL.DTOs.ConnectionTables;
using BL.DTOs.Entities.Book;
using BL.DTOs.Enums;
using BL.Facades;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVCProject.Config;
using MVCProject.Models;
using MVCProject.StateManager;
using MVCProject.StateManager.FilterStates;
using System;
using System.Threading.Tasks;

namespace MVCProject.Controllers
{
    public class BookController : BaseController
    {
        private readonly BookFacade _bookFacade;

        public BookController(BookFacade facade)
        {
            _bookFacade = facade;
        }

        // GET: Book
        [HttpGet]
        public async Task<IActionResult> Index(int page = 1)
        {
            var bookFilterState = TempData.Get<BookFilterState>(TempDataKeys.BookFilter.ToString());
            if (bookFilterState == null)
            {
                bookFilterState = new BookFilterState();
            }

            SetViewDataForIndex(bookFilterState);

            var model = await _bookFacade.GetBookPreviews(page, PageSize, bookFilterState.Title, bookFilterState.AuthorName,
                bookFilterState.AuthorSurname, bookFilterState.Genres, bookFilterState.Language,
                bookFilterState.PageFrom, bookFilterState.PageTo, bookFilterState.ReleaseFrom, bookFilterState.ReleaseTo);

            var pagedModel = new PagedListViewModel<BookPrevDTO>(new PaginationViewModel(page, model.totalNumberOfBooks, PageSize),
                                                                 model.bookPrevs);

            TempData.Put<BookFilterState>(TempDataKeys.BookFilter.ToString(), bookFilterState);
            return View(pagedModel);
        }

        // POST: Book
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(int page,
                                               string title,
                                               string authorName,
                                               string authorSurname,
                                               GenreTypeDTO[] genres,
                                               LanguageDTO? language,
                                               int? pageFrom,
                                               int? pageTo,
                                               DateTime? releaseFrom,
                                               DateTime? releaseTo)
        {
            page = 1;
            var bookFilterState = new BookFilterState()
            {
                Title = title,
                AuthorName = authorName,
                AuthorSurname = authorSurname,
                Genres = genres,
                Language = language,
                PageFrom = pageFrom,
                PageTo = pageTo,
                ReleaseFrom = releaseFrom,
                ReleaseTo = releaseTo
            };

            SetViewDataForIndex(bookFilterState);

            var model = await _bookFacade.GetBookPreviews(page, PageSize, bookFilterState.Title,
                bookFilterState.AuthorName, bookFilterState.AuthorSurname, bookFilterState.Genres,
                bookFilterState.Language, bookFilterState.PageFrom, bookFilterState.PageTo,
                bookFilterState.ReleaseFrom, bookFilterState.ReleaseTo);

            var pagedModel = new PagedListViewModel<BookPrevDTO>(new PaginationViewModel(page, model.totalNumberOfBooks, PageSize),
                                                                 model.bookPrevs);

            TempData.Put<BookFilterState>(TempDataKeys.BookFilter.ToString(), bookFilterState);

            return View(pagedModel);
        }

        private void SetViewDataForIndex(BookFilterState bookFilterState)
        {
            ViewData["eBook"] = false;
            ViewData["bookTitle"] = bookFilterState.Title;
            ViewData["authorName"] = bookFilterState.AuthorName;
            ViewData["authorSurname"] = bookFilterState.AuthorSurname;
            ViewData["genres"] = bookFilterState.Genres;
            ViewData["language"] = bookFilterState.Language;
            ViewData["pageFrom"] = bookFilterState.PageFrom;
            ViewData["pageTo"] = bookFilterState.PageTo;
            ViewData["releaseFrom"] = bookFilterState.ReleaseFrom;
            ViewData["releaseTo"] = bookFilterState.ReleaseTo;
        }

        // GET: Book/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var collectToLoad = new[] { nameof(BookDTO.BookInstances), nameof(BookDTO.Reviews), nameof(BookDTO.Genres) };

            var book = await _bookFacade.Get(id.Value, collectToLoad: collectToLoad);
            if (book == null)
            {
                return NotFound();
            }

            book.Authors = await _bookFacade.GetAuthorBooksByBook(id.Value);

            return View(book);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Details(int? bookId, int? genreId, int? authorId)
        {
            if (!User.IsInRole(GlobalConstants.AdminRoleName))
            {
                return NotFound();
            }

            if (bookId == null)
            {
                return View();
            }

            if (genreId != null)
            {
                _bookFacade.RemoveGenreFromBook(bookId.Value, genreId.Value);
            }
            else if (authorId != null)
            {
                _bookFacade.RemoveAuthorFromBook(bookId.Value, authorId.Value);
            }

            return RedirectToAction(nameof(Details), new { id = bookId });
        }

        // GET: Book/Create
        public IActionResult Create()
        {
            if (!User.IsInRole(GlobalConstants.AdminRoleName))
            {
                return NotFound();
            }

            return View();
        }

        // POST: Book/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,Description,ISBN,PageCount,DateOfRelease,Language,Id")] BookDTO book)
        {
            if (!User.IsInRole(GlobalConstants.AdminRoleName))
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _bookFacade.Create(book);
                return RedirectToAction(nameof(Index));
            }

            return View(book);
        }

        public IActionResult AddGenreToBook(int? id)
        {
            if (!User.IsInRole(GlobalConstants.AdminRoleName))
            {
                return NotFound();
            }

            if (id == null)
            {
                return NotFound();
            }

            StateKeeper.Instance.AddTillNextRequest(this, TempDataKeys.BookDTOId, id.Value);

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddGenreToBook(int id, [Bind("GenreID,BookID")] BookGenreDTO newBookGenreEntry)
        {
            if (id != newBookGenreEntry.BookID || !User.IsInRole(GlobalConstants.AdminRoleName))
            {
                return NotFound();
            }

            StateKeeper.Instance.SaveSpecificObjectForNextRequest(this, TempDataKeys.BookDTOId);

            if (!ModelState.IsValid)
            {
                return View();
            }

            await _bookFacade.AddGenreToBook(newBookGenreEntry);

            return RedirectToAction(nameof(Details), new { id = newBookGenreEntry.BookID });
        }

        public async Task<IActionResult> AddAuthorToBook(int? id)
        {
            if (!User.IsInRole(GlobalConstants.AdminRoleName))
            {
                return NotFound();
            }

            if (id == null)
            {
                return NotFound();
            }

            // Put all ids
            ViewData["authors"] = await _bookFacade.GetAllAuthors();

            StateKeeper.Instance.AddTillNextRequest(this, TempDataKeys.BookDTOId, id.Value);

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddAuthorToBook(int id, [Bind("AuthorID,BookID")] AuthorBookDTO newBookGenreEntry)
        {
            if (id != newBookGenreEntry.BookID || !User.IsInRole(GlobalConstants.AdminRoleName))
            {
                return NotFound();
            }

            StateKeeper.Instance.SaveSpecificObjectForNextRequest(this, TempDataKeys.BookDTOId);

            if (!ModelState.IsValid)
            {
                return View();
            }

            await _bookFacade.AddAuthorToBook(newBookGenreEntry);

            return RedirectToAction(nameof(Details), new { id = newBookGenreEntry.BookID });
        }

        // GET: Book/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || !User.IsInRole(GlobalConstants.AdminRoleName))
            {
                return NotFound();
            }

            var book = await _bookFacade.Get(id.Value);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        // POST: Book/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Title,Description,ISBN,PageCount,DateOfRelease,Language,Id")] BookDTO book)
        {
            if (id != book.Id || !User.IsInRole(GlobalConstants.AdminRoleName))
            {
                return NotFound();

TeamProject (Book Reservation)/MVCProject/Views/Shared/_Layout.cshtml
@using MVCProject.StateManager
@using MVCProject.Config 

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookRentalService</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Book Rental Service</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EBook" asp-action="Index">E-Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EReaderInstance" asp-action="Index">E-Readers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="Index">Authors</a>
                        </li>
                    </ul>

                    @if (!User.Identity.IsAuthenticated)
                    {
                        <ul class="navbar-nav flex-grow-0" style="text-align:right;">
                            <li style="text-align:right;">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Register">Register</a>
                            </li>
                            <li style="text-align:right;">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">Login</a>
                            </li>
                        </ul>
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        <ul class="navbar-nav flex-grow-0" style="text-align:right;">
                            <li style="text-align:right;">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="MyAccount">My Account</a>
                            </li>
                            @if (StateKeeper.Instance.GetReservationInSession(Context.Session) != null)
                            {
                                <li style="text-align:right;">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Reservation" asp-action="DetailsCurrent">Active reservation</a>
                                </li>
                            }
                            <li style="text-align:right;">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">Logout</a>
                            </li>
                        </ul>
                    }
                    @if (User.IsInRole(GlobalConstants.AdminRoleName))
                    {
                        <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Main">SuperAdminButton</a>
                    }

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MVCProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TeamProject (Book Reservation)/MVCProject/Views/Shared/_PaginationPartial.cshtml
@model MVCProject.Models.PaginationViewModel

<ul class="pagination justify-content-center">
    <li><a class="waves-effect orange lighten-3" href="?page=@Model.LeftBound"><<</a></li>
    @if (Model.Current - 1 >= Model.LeftBound)
    {
        <li><a class="waves-effect orange lighten-3" href="?page=@(Model.Current-1)">&lt;</a></li>
    }
    @for (var i = Model.LeftBound; i <= Model.RightBound; i++)
    {
        if (i == Model.Current)
        {
            <li class="orange lighten-3 active"><a href="?page=@i">@i</a></li>
        }
        else
        {
            <li><a class="waves-effect orange lighten-3" href="?page=@i">@i</a></li>
        }
    }
    @if (Model.Current + 1 <= Model.Last)
    {
        <li><a class="waves-effect orange lighten-3" href="?page=@(Model.Current+1)">></a></li>
    }
    <li><a class="waves-effect orange lighten-3" href="?page=@Model.Last">>></a></li>
</ul>